name: CI

on:
  push:
    branches:
      - '*'  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x.x'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier to check code formatting
        run: npm run format -- --check  

      - name: Run ESLint to lint code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x.x'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test
