name: CI

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x.x'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier to check code formatting
        run: npm run format:check

      - name: Run ESLint to lint code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x.x'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test

  docs:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npm run jsdoc

      - name: Format all files with Prettier
        run: npm run format

      - name: Commit and push updated JSDoc (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add jsdocs/
          if git diff --cached --quiet; then
            echo "No changes in docs"
          else
            git commit -m "Auto-update JSDoc"
            git push
          fi
